name: Quick Test

on:
  push:
    branches: [ add-unit-testing ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'test_runner.py'
      - 'requirements.txt'
  pull_request:
    branches: [ add-unit-testing ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'test_runner.py'
      - 'requirements.txt'

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run quick unit tests
      run: |
        python test_runner.py --module all --type unit --verbose
    
    - name: Run linting
      run: |
        python test_runner.py --lint --verbose
